---
- hosts: vagrant
  remote_user: vagrant
  become: true
  become_user: root
  tasks:
  - name: ls
    command: ls
  - name: start
    command: microk8s start
  - name: run Kubernetes
    command: microk8s kubectl get all --all-namespaces
